package com.cwjcsu.ybjj.domain;

import com.cwjcsu.ybjj.domain.enums.LoginResult;
import com.cwjcsu.ybjj.domain.enums.LoginType;
import java.util.Date;

public class LoginHistory extends AbstractEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.login_type
     *
     * @mbggenerated
     */
    private LoginType loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.result
     *
     * @mbggenerated
     */
    private LoginResult result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.client_ip
     *
     * @mbggenerated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.user_agent
     *
     * @mbggenerated
     */
    private String userAgent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.id
     *
     * @return the value of login_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.id
     *
     * @param id the value for login_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.user_id
     *
     * @return the value of login_history.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.user_id
     *
     * @param userId the value for login_history.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.login_time
     *
     * @return the value of login_history.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.login_time
     *
     * @param loginTime the value for login_history.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.login_type
     *
     * @return the value of login_history.login_type
     *
     * @mbggenerated
     */
    public LoginType getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.login_type
     *
     * @param loginType the value for login_history.login_type
     *
     * @mbggenerated
     */
    public void setLoginType(LoginType loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.result
     *
     * @return the value of login_history.result
     *
     * @mbggenerated
     */
    public LoginResult getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.result
     *
     * @param result the value for login_history.result
     *
     * @mbggenerated
     */
    public void setResult(LoginResult result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.client_ip
     *
     * @return the value of login_history.client_ip
     *
     * @mbggenerated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.client_ip
     *
     * @param clientIp the value for login_history.client_ip
     *
     * @mbggenerated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.user_agent
     *
     * @return the value of login_history.user_agent
     *
     * @mbggenerated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.user_agent
     *
     * @param userAgent the value for login_history.user_agent
     *
     * @mbggenerated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }
}