package com.cwjcsu.ybjj.domain;

import java.util.Date;

public class UserWebToken extends AbstractEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_web_token.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_web_token.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_web_token.token_id
     *
     * @mbggenerated
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_web_token.expire_time
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_web_token.delete_on_session_destroy
     *
     * @mbggenerated
     */
    private Boolean deleteOnSessionDestroy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_web_token.open_account_id
     *
     * @mbggenerated
     */
    private Integer openAccountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_web_token.id
     *
     * @return the value of user_web_token.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_web_token.id
     *
     * @param id the value for user_web_token.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_web_token.user_id
     *
     * @return the value of user_web_token.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_web_token.user_id
     *
     * @param userId the value for user_web_token.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_web_token.token_id
     *
     * @return the value of user_web_token.token_id
     *
     * @mbggenerated
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_web_token.token_id
     *
     * @param tokenId the value for user_web_token.token_id
     *
     * @mbggenerated
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_web_token.expire_time
     *
     * @return the value of user_web_token.expire_time
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_web_token.expire_time
     *
     * @param expireTime the value for user_web_token.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_web_token.delete_on_session_destroy
     *
     * @return the value of user_web_token.delete_on_session_destroy
     *
     * @mbggenerated
     */
    public Boolean getDeleteOnSessionDestroy() {
        return deleteOnSessionDestroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_web_token.delete_on_session_destroy
     *
     * @param deleteOnSessionDestroy the value for user_web_token.delete_on_session_destroy
     *
     * @mbggenerated
     */
    public void setDeleteOnSessionDestroy(Boolean deleteOnSessionDestroy) {
        this.deleteOnSessionDestroy = deleteOnSessionDestroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_web_token.open_account_id
     *
     * @return the value of user_web_token.open_account_id
     *
     * @mbggenerated
     */
    public Integer getOpenAccountId() {
        return openAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_web_token.open_account_id
     *
     * @param openAccountId the value for user_web_token.open_account_id
     *
     * @mbggenerated
     */
    public void setOpenAccountId(Integer openAccountId) {
        this.openAccountId = openAccountId;
    }
}