package com.cwjcsu.ybjj.domain;

import java.util.Date;

public class UserSession extends AbstractEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.token_id
     *
     * @mbggenerated
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.expire_time
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.id
     *
     * @return the value of user_session.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.id
     *
     * @param id the value for user_session.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.user_id
     *
     * @return the value of user_session.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.user_id
     *
     * @param userId the value for user_session.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.token_id
     *
     * @return the value of user_session.token_id
     *
     * @mbggenerated
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.token_id
     *
     * @param tokenId the value for user_session.token_id
     *
     * @mbggenerated
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.expire_time
     *
     * @return the value of user_session.expire_time
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.expire_time
     *
     * @param expireTime the value for user_session.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}